# Generated by Django 4.0.3 on 2022-04-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
