# Generated by Django 4.0.3 on 2022-04-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
